version: '3.9'

services:
  frontend:
    build:
      context: ./client-form  # Caminho para o diretório do frontend (client-form)
      dockerfile: Dockerfile  # Usar o Dockerfile no diretório do frontend
    ports:
      - "3001:80"  # Mapear a porta 80 do contêiner para a porta 3001 no host
    networks:
      - app-network  # Conectar o frontend à rede personalizada

networks:
  app-network: