#version: '3.9'

#services:
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile  
#    ports:
#      - "3001:80"  
#    volumes:
#      - ./client-form:/app/client-form  

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile  
#    ports:
#      - "3000:3000"  
#    volumes:
#      - ./api-app:/app/api-app  
 #   environment:
  #    - DATABASE_HOST=postgres  
   #   - DATABASE_PORT=5432  
    #depends_on:
     # - postgres  

  #postgres:
   # image: postgres:15
   # container_name: nest_postgres
   # restart: always
   # ports:
   #   - "5432:5432"  
   # environment:
   #   POSTGRES_USER: postgres
   #   POSTGRES_PASSWORD: postgres
   #   POSTGRES_DB: nest_db
   # volumes:
   #   - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
